const PATCH_NOTE_DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/
const PATCH_NOTE_VERSION_PATTERN = /^v?(\d+)\.(\d+)\.(\d+)(?:-([0-9a-z.-]+))?$/i

/** 패치노트 분류와 표시 순서를 소유하는 클래스형 enum. */
export class PatchNoteCategory {
    private static readonly all: PatchNoteCategory[] = []
    readonly key: string
    readonly marker: '+' | '/' | '-'
    readonly label: string

    static readonly FEATURE_ADDED = new PatchNoteCategory('feature-added', '+', '추가된 기능')
    static readonly CONTENT_ADDED = new PatchNoteCategory('content-added', '+', '추가된 콘텐츠')
    static readonly CHANGED = new PatchNoteCategory('changed', '/', '수정된 기능')
    static readonly REMOVED = new PatchNoteCategory('removed', '-', '삭제된 기능·콘텐츠')

    private constructor(key: string, marker: '+' | '/' | '-', label: string) {
        this.key = key
        this.marker = marker
        this.label = label
        PatchNoteCategory.all.push(this)
    }

    static values(): readonly PatchNoteCategory[] { return PatchNoteCategory.all }
    static fromKey(key: string): PatchNoteCategory | undefined {
        return PatchNoteCategory.all.find(category => category.key === key.trim().toLowerCase())
    }
}

interface PatchNoteSectionDefinition {
    readonly category: PatchNoteCategory
    readonly items: readonly string[]
}

interface PatchNoteDefinition {
    readonly version: string
    readonly releasedAt: string
    readonly sections: readonly PatchNoteSectionDefinition[]
}

type PatchNoteSectionInput = readonly [PatchNoteCategory, ...string[]]

export interface PatchNoteSectionSnapshot {
    readonly categoryKey: string
    readonly categoryMarker: '+' | '/' | '-'
    readonly categoryLabel: string
    readonly items: readonly string[]
}

export interface PatchNoteSnapshot {
    readonly version: string
    readonly releasedAt: string
    readonly sections: readonly PatchNoteSectionSnapshot[]
}

/**
 * 사용자에게 공개할 버전별 변경 기록의 단일 기준.
 * 새 패치는 가장 위에 쓰지 않아도 getPatchNotes()가 SemVer 역순으로 정렬한다.
 */
function definePatchNote(
    version: string,
    releasedAt: string,
    ...sections: PatchNoteSectionInput[]
): PatchNoteDefinition {
    return {
        version,
        releasedAt,
        sections: sections.map(([category, ...items]) => ({ category, items })),
    }
}

const FEATURE = PatchNoteCategory.FEATURE_ADDED
const CONTENT = PatchNoteCategory.CONTENT_ADDED
const CHANGED = PatchNoteCategory.CHANGED

const PATCH_NOTES: readonly PatchNoteDefinition[] = [
    definePatchNote('1.0.5', '2026-07-24',
        [CHANGED,
            '보스 기술의 시전 예고를 채팅 기록에도 남기고, 적중·회피 메시지에서 기술명과 상태이상 효과를 확인할 수 있게 개선했습니다.',
        ],
    ),
    definePatchNote('1.0.4', '2026-07-24',
        [FEATURE,
            '지도에서 방문한 장소를 선택해 확인 한 번으로 해당 장소까지 자동이동할 수 있게 했습니다.',
            '행동·처치·스탯 조건으로 획득하고 하나를 장착해 고유 패시브를 받는 칭호 시스템을 추가했습니다.',
            '칭호 목록·장착·장착 해제 명령과 보유 칭호 자동완성을 추가했습니다.',
            '관리자 페이지와 관리자 명령에서 플레이어의 칭호를 부여하거나 삭제할 수 있게 했습니다.',
            '마도 대장장이는 지팡이 틀을 단조한 뒤 전용 마력 부여로 실제 지팡이를 완성할 수 있습니다.',
            '기계 장인은 활대·화살촉을 단조하고 시위·화살대와 조립해 커스텀 활과 화살을 만들 수 있습니다.',
        ],
        [CONTENT,
            '레거시 칭호 16종과 슬라임·보스·채광·낚시·단조·원소 성장 칭호 6종을 추가했습니다.',
            '호환 섬유를 사용하는 강화 활시위와 나무 화살대 제작법, 엘리트 대장장이 전용 단조 부품을 추가했습니다.',
        ],
        [CHANGED,
            '바닥 아이템을 번호와 개수로 지정해 묶음 중 필요한 수량만 주울 수 있게 했습니다.',
            '홍염산지 3으로 향하는 모든 경로에 동일한 Lv.36 제한을 적용했습니다.',
            '공격 중 주무기의 내구도가 다해 파괴되면 채팅 메시지와 알림으로 함께 안내하도록 수정했습니다.',
            '전체 업데이트 기록을 작업 묶음별 버전으로 다시 나누고, 튜토리얼 완성까지의 기록은 베타 버전으로 구분했습니다.',
            '패치노트 명령의 전체 변경 기록을 상세보기 안에 접어 채팅을 짧게 표시하도록 개선했습니다.',
            'PC 지도에서 장소를 클릭하면 드래그로만 처리되던 문제를 수정했습니다.',
            '모바일에서 메시지 안의 명령·상세보기 버튼을 눌러도 채팅 키보드가 닫히지 않도록 수정했습니다.',
            '장착 칭호가 채팅 닉네임, 상태 HUD와 상태창에 표시되도록 했습니다.',
            '관리자 입력창의 검색 목록이 다이얼로그 안에서 잘리던 문제를 수정하고 화면 여유 공간에 맞춰 표시되도록 개선했습니다.',
            '투사체 가속이 비행시간뿐 아니라 화살과 마법 투사체의 적중률에도 균형 있게 반영되도록 수정했습니다.',
            'PVP 칭호 학살자는 100킬, 상위 칭호 몰살자는 500킬에 획득하도록 조건을 분리했습니다.',
            '양쪽 1시간 이상 플레이·30레벨 이내 격차·부활 후 60초·동일 상대 24시간 1회 조건을 통과한 PVP 처치만 칭호 진행도와 영웅 효과에 인정하도록 수정했습니다.',
            '새싹 표시는 누적 플레이 24시간 또는 Lv.30 중 하나를 먼저 달성하면 사라지도록 변경했습니다.',
            '순위 비공개 플레이어를 공개 순위 계산에서 제외하고 실제 순위와 수치를 알 수 없는 하단 별도 구역에 표시하도록 변경했습니다.',
            '루미나르 잡화점에 Lv.20 성장용 성휘목 지팡이를 추가하고 견습·성휘목·애도목 지팡이의 마법력과 투사체 성능을 성장 구간에 맞게 조정했습니다.',
            '지팡이 기본 마력 구체의 피해를 높이고 룬 제련사의 전투 룬각에 공격속도 증가를 추가했습니다.',
            '마도 결속 단조 각인의 마법력이 감각에 따라 끝없이 커지지 않고 제작자 레벨과 감각의 완만한 곡선 및 상한을 따르도록 조정했습니다.',
            '관리자 밸런스 프로파일이 레벨별 실제 추천 장비와 투사체 가속·투사체 피해 계수로 적중률과 평타 피해를 계산하도록 보정했습니다.',
            '황혼왕릉을 거쳐 천둥마루의 Lv.50 관문을 우회하던 자동이동 경로를 차단했습니다.',
            '줍기·버리기·장착·장착 해제의 결과는 비공개인데 명령문만 다른 사용자에게 보이던 문제를 수정했습니다.',
            '부활할 때 정신력도 최대치까지 회복되도록 수정했습니다.',
            '정신력 스탯 1당 최대 정신력 증가량을 5에서 5.25로 소폭 높였습니다.',
        ],
    ),
    definePatchNote('1.0.3', '2026-07-23',
        [FEATURE,
            '패치노트를 날짜가 아닌 배포 버전별로 선택해 확인할 수 있게 했습니다.',
        ],
        [CONTENT,
            '금속 단조에 투구·흉갑·각반·철갑화를 추가해 방어구도 직접 제작할 수 있게 했습니다.',
        ],
        [CHANGED,
            '낚시와 단조 경험치가 희귀도·완성품 레벨·품질에 따라 동레벨 사냥 보상에 맞춰 증가하도록 조정했습니다.',
            '감정 화면에서 같은 능력치의 단조 보정이 여러 줄로 반복되지 않고 한 줄로 합쳐지도록 수정했습니다.',
        ],
    ),
    definePatchNote('1.0.2', '2026-07-23',
        [CHANGED,
            '궁수는 공격력과 이동속도, 암살자는 이동속도와 공격력 중심으로 기본·성장 스킬 계수를 개편했습니다.',
            '엘리트 스킬은 메인 직업의 대표 능력치가 서브 직업보다 크게 기여하도록 조정했습니다.',
            '직업 버프가 공격 기술의 피해와 일부 지속시간도 자연스럽게 증폭하도록 조정했습니다.',
        ],
    ),
    definePatchNote('1.0.1', '2026-07-23',
        [FEATURE,
            '입력창에서 채널·근처·파티·광고 채팅을 선택할 수 있게 했습니다.',
            '관리자는 모든 채널에 표시되는 공지 채팅을 선택할 수 있게 했습니다.',
            '귓속말을 회색으로 구분하고 @ 입력 중 채팅 타입 버튼에도 귓속말 대상을 표시하도록 개선했습니다.',
        ],
    ),
    definePatchNote('1.0.0', '2026-07-23',
        [FEATURE,
            '악행과 플레이어 처치로 누적되고 시간·사망·교단 헌금으로 감소하는 카르마 시스템을 추가했습니다.',
            '고카르마 사망 패널티, 질서 시설 이용 제한과 현상 대상 처치자의 영웅 효과를 적용했습니다.',
            '햄버거 메뉴와 /패치노트 명령에서 변경 기록을 확인할 수 있게 했습니다.',
            '공개 채팅 메시지에 답장하고 원문 요약을 눌러 해당 메시지 위치로 이동할 수 있게 했습니다.',
        ],
        [CONTENT,
            '전사·궁수·암살자·마법사·대장장이의 Lv.75/100/140/180 성장 스킬과 상위 속성 주문을 추가했습니다.',
        ],
        [CHANGED,
            '악명 단계 플레이어의 채팅 닉네임 옆에 🥀 표식을 표시하고 관리자 페이지에서 카르마를 확인·설정할 수 있게 했습니다.',
        ],
    ),
    definePatchNote('0.68.0', '2026-07-23',
        [FEATURE,
            '방문 장소를 대상으로 띄어쓰기·부분 이름·유사도를 지원하는 자동이동과 이동 취소 명령을 추가했습니다.',
            '게임 방법과 콘텐츠를 계층별로 읽을 수 있는 게임 안내 페이지를 추가했습니다.',
            '계정 정보는 보존하면서 게임 진행 데이터만 초기화하는 운영 기능을 추가했습니다.',
            '누적 플레이 24시간 미만 플레이어의 이름 옆에 🌱 표식을 표시하도록 했습니다.',
            '실제 장소와 행동 성공을 확인하며 진행하는 첫 모험 튜토리얼을 완성했습니다.',
        ],
        [CONTENT,
            '역설기계고, 잿빛심연, 공허왕관 성채, 월식해구, 역근수해·태초심장 권역을 추가했습니다.',
            '각 후반 권역에 분기 경로, 지역 재료와 장비, 상점, 연속 퀘스트와 서로 다른 중간·최종 보스를 배치했습니다.',
        ],
        [CHANGED,
            '모든 마법의 공용 재사용 대기시간을 0.5초, 같은 속성 마법은 1초로 조정했습니다.',
            '튜토리얼이 잘못된 명령이나 실제로 완료하지 않은 낚시·광질·사냥을 성공으로 처리하지 않도록 수정했습니다.',
        ],
    ),
    definePatchNote('0.67.0', '2026-07-22',
        [CONTENT,
            '안개수령 해안과 침몰왕도 권역, 지역 몬스터·보스·보상·이동 경로를 추가했습니다.',
        ],
    ),
    definePatchNote('0.66.0', '2026-07-22',
        [CHANGED,
            '스킬 효과와 발동 조건을 불필요한 개발 용어 없이 자연스러운 한국어 문장과 실제 적용 수치로 다시 작성했습니다.',
            '최종 수치는 간결하게 보여주고 상세 계수는 툴팁에서 확인할 수 있게 정리했습니다.',
        ],
    ),
    definePatchNote('0.65.0', '2026-07-22',
        [FEATURE,
            '스킬 정의에 태그 기반 공유 재사용 대기시간을 추가했습니다.',
            '감각으로 얻는 치명타율이 50%에 가까워질수록 증가 효율이 완만해지도록 제한했습니다.',
            '한글 초성 닉네임도 사용할 수 있게 했습니다.',
        ],
        [CONTENT,
            '은빛거미숲, 황혼왕릉, 유리사막, 서리장막과 얼음궁전 권역을 추가했습니다.',
            '저주·석화·열병 상태이상과 Lv.50~200 직업 성장 스킬을 확장했습니다.',
        ],
        [CHANGED,
            '사망 상태로 다시 접속할 때 사망 패널티가 중복 적용되지 않도록 수정했습니다.',
        ],
    ),
    definePatchNote('0.64.0', '2026-07-19',
        [FEATURE,
            '두 플레이어가 아이템과 골드를 안전하게 확인한 뒤 교환하는 거래 기능을 추가했습니다.',
        ],
        [CHANGED,
            '모바일 단조 입력이 키보드를 열지 않고 노트 간격과 판정이 명확해지도록 개선했습니다.',
            '단조 장비 능력치를 제작자 숙련도에 맞게 높이고, 바닥 아이템에도 개별 이름이 표시되게 했습니다.',
            '채팅을 위로 읽는 동안 강제 부드러운 자동 스크롤이 발생하지 않도록 수정했습니다.',
            '마법부여 설명에 실제로 부여되는 상태효과와 의미를 표시하도록 개선했습니다.',
        ],
    ),
    definePatchNote('0.63.0', '2026-07-19',
        [FEATURE,
            '단조 장비에 재료·품질·무기 성향을 반영한 결정적 RPG 이름과 희귀 변형 이름을 생성하도록 했습니다.',
            '장인이 직접 만든 장비에 이름을 붙이고, 마법 대장장이는 무기에 속성 효과를 부여할 수 있게 했습니다.',
            '전투 대장장이는 강화석으로 직접 만든 무기를 최대 5단계까지 강화할 수 있게 했습니다.',
            '관리자가 레벨 변화분만큼 기본 스탯과 스탯 포인트를 조정할 수 있게 했습니다.',
        ],
        [CONTENT,
            '레벨 구간별 보스 관문과 분기형 지역을 추가했습니다.',
            '화산 광물 합금과 전용 고난도 단조 패턴을 추가했습니다.',
        ],
        [CHANGED,
            '제작 정밀도와 대장장이 숙련도가 완성 장비 능력치와 특수 성향에 충분히 반영되도록 조정했습니다.',
        ],
    ),
    definePatchNote('0.62.0', '2026-07-19',
        [FEATURE,
            '대장장이의 단조 경험치와 상태 HUD 경험치 진행도를 추가했습니다.',
            '지도 라벨 크기 조절·표시 전환과 겹침 자동 정리 기능을 추가했습니다.',
        ],
        [CHANGED,
            '재생 효과의 레벨 제한을 없애고 실제 회복량이 체감되도록 강화했습니다.',
            '접속이 끊긴 플레이어가 월드에 남지 않도록 온라인 상태 정리를 수정했습니다.',
            '관리자 검색 드롭다운의 높이와 스크롤 영역을 넓혔습니다.',
            '경험치 표시를 이름·레벨 옆의 작은 진행도로 정리했습니다.',
            '지도 바이옴이 화면 전체에서 거리 기반으로 자연스럽게 혼합되도록 렌더링과 성능을 개선했습니다.',
        ],
    ),
    definePatchNote('0.61.0', '2026-07-19',
        [CONTENT,
            '대장장이를 전직소에서 선택할 수 있는 전직 시험과 퀘스트를 추가했습니다.',
        ],
    ),
    definePatchNote('0.60.0', '2026-07-19',
        [FEATURE,
            '서버 스케줄러·행동 트랜잭션·안전한 상태 동기화 기반을 추가했습니다.',
            '공격 단계별 처리와 몬스터 성향·지능·위협도 AI를 추가했습니다.',
            '관리자가 미니게임과 위험 패턴 프리셋을 플레이어에게 실행할 수 있게 했습니다.',
            'PVP 대상 지정과 안전·중립·적대 지역별 전투 및 사망 규칙을 추가했습니다.',
            '추천 장비·버프·평타·스킬 순환을 포함한 직업 및 장비 전투력 분석을 추가했습니다.',
            '단조 리듬 미니게임, 재료 기반 장비 생성과 대장장이 성장 흐름을 추가했습니다.',
            '투사체 속도가 능력치·스킬 레벨·무기 계수에 따라 빨라지도록 했습니다.',
            '붙여넣기와 여러 장 미리보기를 지원하는 이미지 첨부 대기열을 추가했습니다.',
            '파티원이 서로의 스킬 발동과 전투 결과를 공유하도록 했습니다.',
        ],
        [CONTENT,
            '레거시 상태효과와 속성 간 상쇄·연계 반응을 현재 전투 규칙에 맞게 확장했습니다.',
            '직업 패시브·엘리트 계승 패시브·무기 숙련·스탯 각성·엘리트 액티브 기술을 추가했습니다.',
            'Lv.200 이후 지역, 질문문·유물·파괴문 미궁과 보스 패턴을 추가했습니다.',
        ],
        [CHANGED,
            '지도 바이옴 영역과 색상 전이가 연결된 지역 단위로 보이도록 개선했습니다.',
            '불필요한 직업 스킬 무기 제한을 완화하고 대장장이를 정식 직업 슬롯으로 편입했습니다.',
            '철뿌리 심장수호자와 후속 보스의 피해·CC·미니게임 패턴을 강화하고 서로 다른 경험으로 조정했습니다.',
        ],
    ),
    definePatchNote('0.59.0', '2026-07-18',
        [FEATURE,
            '채팅 이미지 업로드·보관·표시와 제목을 넣을 수 있는 구분선 메시지 컴포넌트를 추가했습니다.',
            '레벨·골드·스탯·능력치별 순위와 카테고리별 공개 설정을 추가했습니다.',
        ],
        [CHANGED,
            '이미지 메시지의 높이와 말풍선 너비가 실제 미디어 크기에 맞게 표시되도록 수정했습니다.',
        ],
    ),
    definePatchNote('0.58.0', '2026-07-18',
        [FEATURE,
            '서버 검증 세션을 사용하는 낚시 미니게임과 낚시 명령·등급표를 추가했습니다.',
            '여러 보호막을 종류·지속시간별로 중첩하고 체력바에 표시하는 보호막 시스템을 추가했습니다.',
        ],
        [CONTENT,
            '다양한 희귀도의 물고기, 미끼, 상점·보물상자 전용 낚싯대를 추가했습니다.',
        ],
        [CHANGED,
            '입질 대기시간, 미끼 묶음 장착, 낚시 게이지와 판정 검증을 조정했습니다.',
            '낚시 미니게임을 단색 면과 명확한 상태색 중심의 간결한 디자인으로 바꿨습니다.',
        ],
    ),
    definePatchNote('0.57.0', '2026-07-18',
        [FEATURE,
            '관리자 페이지에서 플레이어 인벤토리·장비·스탯·스킬·상태이상을 검사하고 조정할 수 있게 했습니다.',
        ],
        [CHANGED,
            '관리자 탭 글자가 잘리지 않도록 레이아웃을 수정했습니다.',
            '여러 접속을 한 사용자도 온라인 인원에 한 번만 집계되도록 수정했습니다.',
        ],
    ),
    definePatchNote('0.56.0', '2026-07-18',
        [FEATURE,
            '공격·이동·상호작용·대상 지정과 스킬을 HUD 퀵 버튼으로 사용할 수 있게 했습니다.',
            '명령어 단축키 목록과 이동·위치·상점·제작·파티 등 주요 명령의 짧은 별칭을 추가했습니다.',
            '스킬 사용 경험치와 레벨 성장 정보를 추가했습니다.',
            '@이름으로 온라인 플레이어에게 귓속말을 보낼 수 있게 했습니다.',
            '관리자 플레이어·월드 관리 페이지와 공지·개별 알림 발송 기능을 추가했습니다.',
            '버리기 묶음 처리, 바닥 아이템 합치기, 장비 파괴, 공복·갈증 상태효과와 부활 회복을 추가했습니다.',
        ],
        [CHANGED,
            '상태창 상세보기를 열기 전에도 기본 정보를 확인할 수 있게 했습니다.',
            '공격과 이동 결과는 관계없는 같은 장소 플레이어에게 방송하지 않도록 했습니다.',
            '지도에 장소별 바이옴 대표색이 표시되도록 했습니다.',
        ],
    ),
    definePatchNote('0.55.0', '2026-07-17',
        [FEATURE,
            '활성화한 스킬 아이콘을 개별 배치하고 쿨타임을 확인하며 즉시 사용하는 스킬 퀵 HUD를 추가했습니다.',
        ],
    ),
    definePatchNote('0.54.0', '2026-07-17',
        [FEATURE,
            '감각에 따라 공개 범위가 넓어지는 아이템 감정과 몬스터 정보 명령을 추가했습니다.',
            '관리자가 방문 여부와 관계없이 전체 장소를 확인하는 전체지도 명령을 추가했습니다.',
        ],
        [CHANGED,
            '감정·몬스터 정보·속성표에서 내부 코드와 개발용 데이터를 숨기고 가공된 정보만 표시하도록 했습니다.',
        ],
    ),
    definePatchNote('0.53.0', '2026-07-17',
        [CHANGED,
            '궁수 화살과 마법 투사체가 소유자의 치명타 확률과 치명타 피해를 이어받도록 수정했습니다.',
        ],
    ),
    definePatchNote('0.52.0', '2026-07-17',
        [CHANGED,
            '채팅 발동어로 스킬을 사용했을 때 시전 문구가 다른 플레이어에게 보이지 않도록 수정했습니다.',
        ],
    ),
    definePatchNote('0.51.0', '2026-07-17',
        [CHANGED,
            '버프 스킬을 사용하면 스킬에 어울리는 발동 메시지와 알림이 표시되도록 개선했습니다.',
        ],
    ),
    definePatchNote('0.50.0', '2026-07-16',
        [CHANGED,
            '강타와 직업 전용 스킬의 피해·소모값·재사용 대기시간을 다시 조정했습니다.',
            '스킬 설명에 실제 적용 수치와 시전어 발동 방법을 더 자세히 표시하도록 했습니다.',
        ],
    ),
    definePatchNote('0.49.0', '2026-07-16',
        [FEATURE,
            '메인·서브 직업, 전직 퀘스트와 조합별 엘리트 직업 시스템을 추가했습니다.',
            '파티 초대·수락·거절·강퇴·해산, 파티 HUD와 경험치 공유를 추가했습니다.',
            '입력창과 명령어에서 정보 열람 공개·비공개 모드를 전환할 수 있게 했습니다.',
        ],
        [CHANGED,
            '상태이상 HUD 아이콘을 작게 조정하고 상세 툴팁을 표시하도록 했습니다.',
            '공개 모드 버튼이 전송 버튼과 같은 크기·모양으로 보이도록 정리했습니다.',
        ],
    ),
    definePatchNote('0.48.0', '2026-07-16',
        [FEATURE,
            '방문한 장소와 연결된 미방문 장소를 확대·축소·이동하며 살펴보는 월드 지도 명령을 추가했습니다.',
            '중요 장소 아이콘, 숨김 장소, 구역·좌표 툴팁을 지도에 표시하도록 했습니다.',
        ],
    ),
    definePatchNote('0.47.0', '2026-07-16',
        [FEATURE,
            '모든 속성의 공격 우세·열세·면역 관계와 아이콘을 확인하는 속성표를 추가했습니다.',
        ],
        [CONTENT,
            '전기·돌·어둠·빛·언데드·신성·벌레·금속·땅 속성과 상성 관계를 추가했습니다.',
        ],
        [CHANGED,
            '공격과 방어 관계를 각각 한 줄씩 나눠 속성표를 읽기 쉽게 했습니다.',
        ],
    ),
    definePatchNote('0.46.0', '2026-07-16',
        [FEATURE,
            '배고픔과 수분의 초당 감소량 능력치를 추가했습니다.',
        ],
        [CHANGED,
            '라이트 테마에서 도움말 설명이 보이지 않던 문제를 수정했습니다.',
        ],
    ),
    definePatchNote('0.45.0', '2026-07-16',
        [FEATURE,
            '생명력·정신력 재생 능력치를 상태창에 표시하고 실제 주기 회복에 적용했습니다.',
            'NPC가 부여하고 이벤트·통계로 목표를 추적하는 퀘스트 시스템을 추가했습니다.',
        ],
        [CHANGED,
            '독 단검의 물리 공격은 속성 면역으로 무효화하지 않고 적중 효과로 독을 부여하도록 분리했습니다.',
            '장착 슬롯 정보가 자동 저장 뒤에도 올바르게 복원되도록 수정했습니다.',
        ],
    ),
    definePatchNote('0.44.0', '2026-07-15',
        [CONTENT,
            '광산에 높은 체력과 스킬 패턴을 가진 보스, 보스 스킬북 보상을 추가했습니다.',
        ],
        [CHANGED,
            '잠긴 길로 이동을 시도하면 공개 가능한 레벨·조건을 함께 안내하도록 했습니다.',
        ],
    ),
    definePatchNote('0.43.0', '2026-07-15',
        [CONTENT,
            '초원·화산·늪·갱도 등 Lv.50까지 이어지는 지역과 레벨별 슬라임·속성 몬스터를 확장했습니다.',
            '장시간 후 다시 상호작용할 수 있는 무작위 보물상자를 여러 장소에 배치했습니다.',
        ],
        [CHANGED,
            '수동 이동이 어려운 특수문자를 장소 이름에서 정리했습니다.',
            '최대 생명력·정신력이 줄면 현재 수치도 새 최대치 이하로 제한되도록 수정했습니다.',
            '상태 HUD 이름 옆에 플레이어 레벨을 표시하도록 했습니다.',
        ],
    ),
    definePatchNote('0.42.0', '2026-07-15',
        [FEATURE,
            '상태창과 HUD에 상태이상 아이콘·레벨·남은 시간·상세 툴팁을 표시하도록 했습니다.',
            '관리자가 대상에게 상태이상을 부여하는 명령을 추가했습니다.',
        ],
        [CHANGED,
            '아이템과 상태이상 아이콘을 밝고 단순한 캐주얼 스타일로 정리했습니다.',
        ],
    ),
    definePatchNote('0.41.0', '2026-07-15',
        [FEATURE,
            '모든 엔티티에 적용 가능한 지속시간·레벨·메타데이터 기반 상태이상 시스템을 추가했습니다.',
            '화염·화상·맹독·마비독 효과와 상태효과 간 적용·교체 규칙을 추가했습니다.',
            '공격자와 대상의 이동속도 차이에 따른 회피와 회피 불가·고정 피해 공격 옵션을 추가했습니다.',
        ],
    ),
    definePatchNote('0.40.0', '2026-07-15',
        [FEATURE,
            '장소별 NPC, 조건부 대사, 선택지, 플래그와 시나리오 이동을 지원하는 대화 시스템을 추가했습니다.',
            '이동·사망·로그아웃·대화 종료 명령으로 진행 중 대화가 안전하게 끝나도록 했습니다.',
        ],
    ),
    definePatchNote('0.39.0', '2026-07-15',
        [FEATURE,
            '재료 조건을 만족하면 발견하고 수량을 지정해 만드는 제작법 시스템을 추가했습니다.',
        ],
        [CONTENT,
            '아이콘이 없던 기존 아이템에 표시용 아이콘을 보강했습니다.',
        ],
        [CHANGED,
            '제작 명령의 레시피 이름과 개수 입력 안내를 분리했습니다.',
            '스킬 발동 문구가 실제 효과보다 먼저 보이도록 순서를 수정했습니다.',
        ],
    ),
    definePatchNote('0.38.0', '2026-07-15',
        [FEATURE,
            '바닥 아이템을 번호나 전체로 줍는 명령과 위치 메시지의 줍기 버튼을 추가했습니다.',
            '아이템별 기본 아이콘과 인스턴스 메타데이터 아이콘 덮어쓰기를 추가했습니다.',
            '장비 내구도와 근접 공격 차감, 진행도 표시를 추가했습니다.',
            '화살 아이템과 마법 구체를 모두 지원하는 소유자 기반 투사체 공격을 추가했습니다.',
            '슬래시 없이 명령어 단축어를 입력하고 자동완성할 수 있게 했습니다.',
            '채굴 도구 제한·드롭·경험치를 가진 자원 오브젝트와 광산을 추가했습니다.',
            '통계·이벤트 기반 스킬 획득과 강타, 대상 지정, 스킬 목록·정보·사용 명령을 추가했습니다.',
        ],
        [CHANGED,
            '개별 아이템 메타데이터는 원본과 다른 값만 저장해 기본 데이터 변경을 이어받도록 했습니다.',
            '몬스터와 자원을 위치의 오브젝트 목록에 함께 표시하고 쓰러진 대상은 뒤로 정렬하도록 했습니다.',
            '모바일에서 메시지를 보낸 뒤 키보드가 깜빡이거나 닫히지 않도록 수정했습니다.',
        ],
    ),
    definePatchNote('0.37.0', '2026-07-14',
        [CHANGED,
            '기존 운영 데이터베이스를 보존한 채 이후 스키마 변경을 적용할 수 있도록 마이그레이션 기준점을 마련했습니다.',
        ],
    ),
    definePatchNote('0.36.0', '2026-07-14',
        [FEATURE,
            '게임 오브젝트 전반에 태그를 부여하고 단방향 속성 상성 배율을 계산하는 시스템을 추가했습니다.',
            '공격자의 물리·마법 관통력과 치명타 확률·피해가 실제 전투에 적용되도록 했습니다.',
        ],
        [CHANGED,
            '프로젝트 구조와 기능별 API를 빠르게 찾을 수 있는 개발 문서 체계를 정리했습니다.',
        ],
    ),
    definePatchNote('0.35.0', '2026-03-14',
        [CHANGED,
            '상태창의 능력치·스탯 설명을 툴팁으로 확인하고 장비 슬롯과 능력치를 일관된 순서로 표시하도록 개선했습니다.',
            'HUD와 툴팁이 겹칠 때 올바른 앞뒤 순서로 보이도록 수정했습니다.',
        ],
    ),
    definePatchNote('0.34.0', '2026-03-11',
        [FEATURE,
            '메시지에 상세 설명을 띄우는 툴팁 컴포넌트를 추가했습니다.',
            '장비·상태·대상 조건에 따라 달라지는 능력치 보정을 지원하도록 했습니다.',
        ],
        [CHANGED,
            '능력치와 스탯의 이름·기본값·표시 규칙을 한 곳에서 일관되게 관리하도록 정리했습니다.',
        ],
    ),
    definePatchNote('0.33.0', '2026-03-03',
        [CHANGED,
            '도움말 명령의 안내 문구와 화면 구성을 읽기 쉽게 개선했습니다.',
        ],
    ),
    definePatchNote('0.32.0', '2026-03-03',
        [CHANGED,
            'HUD의 배치·표시 상태가 일부 상황에서 어긋나던 문제를 수정했습니다.',
        ],
    ),
    definePatchNote('0.31.0', '2026-03-03',
        [FEATURE,
            '몬스터 골드 보상과 장소별 상점·구매 기능을 추가했습니다.',
            '자주 쓰는 명령을 HUD에서 바로 실행하는 퀵슬롯을 추가했습니다.',
        ],
        [CHANGED,
            '장소별 이동 조건과 장비 명령을 정리하고 한글 입력 중 명령이 잘못 전송되는 문제를 수정했습니다.',
        ],
    ),
    definePatchNote('0.30.0', '2026-03-02',
        [FEATURE,
            '관리용 장소 편집기와 플레이어 골드 재화를 추가했습니다.',
        ],
    ),
    definePatchNote('0.29.0', '2026-03-02',
        [FEATURE,
            '플레이어와 몬스터의 사망·처치 흐름을 추가했습니다.',
            '명령어 입력값 자동완성과 텍스트 인자 안내를 추가했습니다.',
        ],
        [CONTENT,
            '전투 흐름을 시험할 수 있는 특수 몬스터를 추가했습니다.',
        ],
    ),
    definePatchNote('0.28.0', '2026-03-01',
        [FEATURE,
            '현재 장소와 연결된 길을 한눈에 보는 미니맵 HUD를 추가했습니다.',
            'HUD별 표시 여부와 세부 설정 화면을 추가했습니다.',
        ],
    ),
    definePatchNote('0.27.0', '2026-02-26',
        [FEATURE,
            '채널 접속 인원 표시와 위치 정보 HUD를 추가했습니다.',
            'HUD를 화면 기준점에 맞춰 자유롭게 배치하고 표시 여부를 저장할 수 있게 했습니다.',
        ],
    ),
    definePatchNote('0.26.0', '2026-02-24',
        [FEATURE,
            '생명력·정신력과 게임 정보를 화면에 고정해서 보는 HUD 시스템을 추가했습니다.',
        ],
        [CHANGED,
            'HUD 기본 위치와 설정 슬라이더 조작을 개선했습니다.',
        ],
    ),
    definePatchNote('0.25.0', '2026-02-24',
        [FEATURE,
            '메시지 버튼에 실행할 명령을 표시할 수 있게 했습니다.',
        ],
        [CHANGED,
            '이동 알림과 메시지 색상 해석이 일관되게 동작하도록 수정했습니다.',
        ],
    ),
    definePatchNote('0.24.0', '2026-02-23',
        [FEATURE,
            '공격·피해·보상과 장비 착용을 포함한 기본 전투 흐름을 추가했습니다.',
            '배고픔·수분·생명력·정신력 저장과 생명력 재생을 추가했습니다.',
            '레벨업 스탯 포인트와 자유 분배를 추가했습니다.',
        ],
        [CHANGED,
            '공격·재생·몬스터 보상·인벤토리 명령의 계산과 표시 오류를 수정했습니다.',
        ],
    ),
    definePatchNote('0.23.0', '2026-02-22',
        [FEATURE,
            '플레이어 생명력과 정신력 자원을 추가했습니다.',
        ],
    ),
    definePatchNote('0.22.0', '2026-02-22',
        [FEATURE,
            '채팅 메시지를 수정·삭제하고 메시지 내부 화면을 닫을 수 있게 했습니다.',
        ],
        [CHANGED,
            '플레이어 상태와 채팅 메시지 구성 흐름을 정리했습니다.',
        ],
    ),
    definePatchNote('0.21.0', '2026-02-21',
        [FEATURE,
            '닉네임 변경과 메시지 버튼 상호작용을 추가했습니다.',
        ],
        [CHANGED,
            '아이템·장소·몬스터 데이터를 일관된 정의 방식으로 정리했습니다.',
        ],
    ),
    definePatchNote('0.20.0', '2026-02-21',
        [CHANGED,
            '햄버거 메뉴의 간격과 모바일 표시를 개선했습니다.',
        ],
    ),
    definePatchNote('0.19.0', '2026-02-21',
        [FEATURE,
            '홈 화면에 생명력·정신력 진행도를 표시했습니다.',
            '여러 대화방을 구분하는 채널과 서버 메시지 방송을 추가했습니다.',
        ],
        [CHANGED,
            '테마 전환 버튼이 화면을 가리지 않도록 투명도를 조정했습니다.',
        ],
    ),
    definePatchNote('0.18.0', '2026-02-20',
        [CHANGED,
            '프로필 이미지 업로드를 메모리에서 안전하게 처리하도록 바꿨습니다.',
            '인증 메일 재전송에 대기시간을 적용했습니다.',
        ],
    ),
    definePatchNote('0.17.0', '2026-02-20',
        [CHANGED,
            '프로필 이미지 업로드에서 비정상 파일과 요청을 차단하도록 보안을 강화했습니다.',
        ],
    ),
    definePatchNote('0.16.0', '2026-02-20',
        [FEATURE,
            '채팅 필터와 기록 탐색, 헤더·햄버거 메뉴, 프로필 변경 화면을 추가했습니다.',
        ],
        [CHANGED,
            '메뉴와 프로필 화면의 표시 오류를 수정했습니다.',
        ],
    ),
    definePatchNote('0.15.0', '2026-02-19',
        [FEATURE,
            '메시지 안에 진행도와 탭 화면을 표현하는 컴포넌트를 추가했습니다.',
        ],
    ),
    definePatchNote('0.14.0', '2026-02-19',
        [FEATURE,
            '공격 가능한 엔티티와 몬스터 데이터 모델을 추가했습니다.',
            '장소와 장소 간 이동을 포함한 월드 시스템을 추가했습니다.',
        ],
    ),
    definePatchNote('0.13.0', '2026-02-18',
        [FEATURE,
            '아이템·인벤토리와 능력치 시스템을 추가했습니다.',
            '명령어별 권한과 공개·비공개 메시지를 추가했습니다.',
        ],
        [CHANGED,
            '비공개 메시지 라벨과 명령 결과 표시를 개선했습니다.',
        ],
    ),
    definePatchNote('0.12.0', '2026-02-17',
        [CHANGED,
            '게임 기능을 일관된 규칙으로 확장할 수 있도록 프로젝트 작업 안내를 정리했습니다.',
        ],
    ),
    definePatchNote('0.11.0', '2026-02-17',
        [FEATURE,
            '조건에 따라 메시지 일부를 숨길 수 있는 표시 컴포넌트를 추가했습니다.',
        ],
        [CHANGED,
            '채팅 메시지 생성 구조를 재사용하기 쉽게 정리했습니다.',
        ],
    ),
    definePatchNote('0.10.0', '2026-02-16',
        [FEATURE,
            '계정과 분리된 플레이어 캐릭터 데이터와 게임 메시지 구분값을 추가했습니다.',
        ],
    ),
    definePatchNote('0.9.0', '2026-02-16',
        [FEATURE,
            '시스템 안내와 명령을 처리하는 채팅 봇 기능을 추가했습니다.',
        ],
        [CHANGED,
            '명령 메시지가 중복 표시되거나 방송 순서가 어긋나던 문제를 수정했습니다.',
        ],
    ),
    definePatchNote('0.8.0', '2026-02-16',
        [CHANGED,
            '기본 프로필 이미지·파비콘 경로와 페이지 언어 정보를 정리했습니다.',
        ],
    ),
    definePatchNote('0.7.0', '2026-02-15',
        [FEATURE,
            '이전 채팅 기록, 게임 알림과 프로필 이미지 기능을 추가했습니다.',
            '알림에서도 채팅과 같은 색상·강조 문법을 사용할 수 있게 했습니다.',
        ],
        [CHANGED,
            '모바일 채팅 입력과 배포 환경의 파일 경로를 안정화했습니다.',
        ],
    ),
    definePatchNote('0.6.0', '2026-02-15',
        [CHANGED,
            '채팅 내부 상세 화면을 열고 닫는 동작이 정상적으로 작동하도록 수정했습니다.',
        ],
    ),
    definePatchNote('0.5.0', '2026-02-15',
        [FEATURE,
            '실시간 채팅 전송·수신의 기본 기능을 추가했습니다.',
        ],
        [CHANGED,
            '안드로이드에서 채팅 화면이 불필요하게 움직이는 문제와 운영 빌드 실행 경로를 수정했습니다.',
        ],
    ),
    definePatchNote('0.4.0', '2026-02-14',
        [FEATURE,
            '서버 사용자 온라인 확인과 채팅 화면 시제품을 추가했습니다.',
        ],
        [CHANGED,
            '잘못된 입력과 비정상 경로 요청을 서버에서 안전하게 거절하도록 했습니다.',
        ],
    ),
    definePatchNote('0.3.0', '2026-02-14',
        [CHANGED,
            '운영 서버의 데이터 연결과 종료 처리가 안정적으로 동작하도록 수정했습니다.',
        ],
    ),
    definePatchNote('0.2.0', '2026-02-13',
        [FEATURE,
            '회원가입·로그인·이메일 인증과 다크 테마를 추가했습니다.',
        ],
        [CHANGED,
            '만료되거나 유효하지 않은 로그인 상태를 실시간 연결에서 즉시 안내하도록 했습니다.',
        ],
    ),
    definePatchNote('0.1.0', '2026-02-07',
        [FEATURE,
            'DaclionOnline의 웹 클라이언트와 게임 서버 초기 실행 기반을 마련했습니다.',
        ],
        [CHANGED,
            '개발·운영 환경에서 같은 코드가 빌드되고 실행되도록 기본 설정을 정리했습니다.',
        ],
    ),
]

export function getPatchNotes(): PatchNoteSnapshot[] {
    return [...PATCH_NOTES]
        .sort((left, right) => comparePatchNoteVersions(right.version, left.version))
        .map(toSnapshot)
}

export function getPatchNote(versionInput: string): PatchNoteSnapshot | undefined {
    const version = normalizePatchNoteVersionInput(versionInput)
    const note = PATCH_NOTES.find(candidate => candidate.version === version)
    return note ? toSnapshot(note) : undefined
}

export function formatPatchNoteVersion(version: string): string {
    const normalized = normalizePatchNoteVersionInput(version)
    return PATCH_NOTE_VERSION_PATTERN.test(normalized) ? `v${normalized}` : version
}

export function formatPatchNoteDate(date: string): string {
    if (!PATCH_NOTE_DATE_PATTERN.test(date)) return date
    const [year, month, day] = date.split('-').map(Number)
    return `${year}년 ${month}월 ${day}일`
}

function normalizePatchNoteVersionInput(input: string): string {
    const trimmed = input.trim()
    const match = trimmed.match(PATCH_NOTE_VERSION_PATTERN)
    if (!match) return trimmed
    const [, major, minor, patch, prerelease] = match
    return `${Number(major)}.${Number(minor)}.${Number(patch)}${prerelease ? `-${prerelease.toLowerCase()}` : ''}`
}

function comparePatchNoteVersions(left: string, right: string): number {
    const leftMatch = normalizePatchNoteVersionInput(left).match(PATCH_NOTE_VERSION_PATTERN)
    const rightMatch = normalizePatchNoteVersionInput(right).match(PATCH_NOTE_VERSION_PATTERN)
    if (!leftMatch || !rightMatch) return left.localeCompare(right)
    for (let index = 1; index <= 3; index++) {
        const difference = Number(leftMatch[index]) - Number(rightMatch[index])
        if (difference !== 0) return difference
    }
    const leftPrerelease = leftMatch[4]
    const rightPrerelease = rightMatch[4]
    if (!leftPrerelease && rightPrerelease) return 1
    if (leftPrerelease && !rightPrerelease) return -1
    return (leftPrerelease ?? '').localeCompare(rightPrerelease ?? '', undefined, { numeric: true })
}

function toSnapshot(note: PatchNoteDefinition): PatchNoteSnapshot {
    return {
        version: note.version,
        releasedAt: note.releasedAt,
        sections: note.sections.map(section => ({
            categoryKey: section.category.key,
            categoryMarker: section.category.marker,
            categoryLabel: section.category.label,
            items: [...section.items],
        })),
    }
}
