import { initGeneralCommands } from "./community/general.js";
import { initPlayerCommands } from "./player/player.js";
import { initAdminCommands } from "./operations/admin.js";
import { initLocationCommands } from "./world/location.js";
import { initShopCommands } from "./economy/shop.js";
import { initSkillCommands } from "./player/skill.js";
import { initProgressCommands } from "./player/progress.js";
import { initCraftingCommands } from "./economy/crafting.js";
import { initNpcCommands } from "./world/npc.js";
import { initQuestCommands } from './world/quest.js';
import { initAffinityCommands } from './world/affinity.js';
import { initMapCommands } from './world/map.js';
import { initCareerCommands } from './player/career.js';
import { initPartyCommands } from './community/party.js';
import { initInspectionCommands } from './player/inspection.js';
import { initFishingCommands } from './economy/fishing.js';
import { initRankingCommands } from './player/ranking.js';
import { initBalanceCommands } from './operations/balance.js';
import { initForgingCommands } from './economy/forging.js';
import { initPuzzleCommands } from './world/puzzle.js';
import { initTradeCommands } from './community/trade.js';
import { initTutorialCommands } from './player/tutorial.js';
import { initKarmaCommands } from './player/karma.js';
import { initPatchNoteCommands } from './operations/patchNotes.js';
import { initTitleCommands } from './player/title.js';
import { initCodexCommands } from './world/codex.js';
import { initMailboxCommands } from './community/mailbox.js';
import { initAlchemyCommands } from './economy/alchemy.js';
import { initCosmeticCommands } from './community/cosmetics.js';
import { initTravelHubCommands } from './world/travelHub.js';

export function initAllCommands(): void {
    initGeneralCommands();
    initPlayerCommands();
    initAdminCommands();
    initLocationCommands();
    initShopCommands();
    initSkillCommands();
    initProgressCommands();
    initCraftingCommands();
    initNpcCommands();
    initQuestCommands();
    initAffinityCommands();
    initMapCommands();
    initCareerCommands();
    initPartyCommands();
    initInspectionCommands();
    initFishingCommands();
    initRankingCommands();
    initBalanceCommands();
    initForgingCommands();
    initPuzzleCommands();
    initTradeCommands();
    initTutorialCommands();
    initKarmaCommands();
    initPatchNoteCommands();
    initTitleCommands();
    initCodexCommands();
    initMailboxCommands();
    initAlchemyCommands();
    initCosmeticCommands();
    initTravelHubCommands();
}
