import { initGeneralCommands } from "./general.js";
import { initPlayerCommands } from "./player.js";
import { initAdminCommands } from "./admin.js";
import { initLocationCommands } from "./location.js";
import { initShopCommands } from "./shop.js";
import { initSkillCommands } from "./skill.js";
import { initProgressCommands } from "./progress.js";
import { initCraftingCommands } from "./crafting.js";
import { initNpcCommands } from "./npc.js";
import { initQuestCommands } from './quest.js';
import { initAffinityCommands } from './affinity.js';
import { initMapCommands } from './map.js';
import { initCareerCommands } from './career.js';
import { initPartyCommands } from './party.js';
import { initInspectionCommands } from './inspection.js';
import { initFishingCommands } from './fishing.js';
import { initRankingCommands } from './ranking.js';
import { initBalanceCommands } from './balance.js';
import { initForgingCommands } from './forging.js';
import { initPuzzleCommands } from './puzzle.js';
import { initTradeCommands } from './trade.js';
import { initTutorialCommands } from './tutorial.js';
import { initKarmaCommands } from './karma.js';
import { initPatchNoteCommands } from './patchNotes.js';
import { initTitleCommands } from './title.js';

export function initAllCommands(): void {
    initGeneralCommands();
    initPlayerCommands();
    initAdminCommands();
    initLocationCommands();
    initShopCommands();
    initSkillCommands();
    initProgressCommands();
    initCraftingCommands();
    initNpcCommands();
    initQuestCommands();
    initAffinityCommands();
    initMapCommands();
    initCareerCommands();
    initPartyCommands();
    initInspectionCommands();
    initFishingCommands();
    initRankingCommands();
    initBalanceCommands();
    initForgingCommands();
    initPuzzleCommands();
    initTradeCommands();
    initTutorialCommands();
    initKarmaCommands();
    initPatchNoteCommands();
    initTitleCommands();
}
